### ISSUE TITLE
请问你的keras和tensorflow的版本是什么

### ISSUE THREAD

**Issue by CerryXu** [GlassyWing/transformer-word-segmenter#12]
`Using TensorFlow backend.
Traceback (most recent call last):
  File "E:/AI/Attention/transformer-word-segmenter/examples/decode_example.py", line 3, in <module>
    from tf_segmenter import get_or_create, TFSegmenter
  File "E:\AI\Attention\transformer-word-segmenter\tf_segmenter\__init__.py", line 21, in <module>
    from keras_transformer.transformer import TransformerACT, TransformerBlock
  File "E:\Python\Anaconda3\envs\your_env_name\lib\site-packages\keras_transformer\transformer.py", line 12, in <module>
    from keras.layers import Layer, Add, Activations, Dropout
ImportError: cannot import name 'Activations'`

我运行工厂函数 get_or_create就会出现这种错误

**Comment by sjzryf** [comment]
你好，解决了吗，我也遇到了同样的问题

**Comment by wuyun-926** [comment]
me too
